/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SafeguardingPolicyRouteImport } from './routes/safeguarding-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NewsroomRouteImport } from './routes/newsroom'
import { Route as GetHelpRouteImport } from './routes/get-help'
import { Route as DonationPolicyRouteImport } from './routes/donation-policy'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DesignUiInspoRouteImport } from './routes/design-ui-inspo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatWeDoIndexRouteImport } from './routes/what-we-do.index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ImpactIndexRouteImport } from './routes/impact.index'
import { Route as GetInvolvedIndexRouteImport } from './routes/get-involved.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as WhatWeDoSocialGrowthRouteImport } from './routes/what-we-do.social-growth'
import { Route as WhatWeDoMentalWellbeingRouteImport } from './routes/what-we-do.mental-wellbeing'
import { Route as WhatWeDoInclusiveCareRouteImport } from './routes/what-we-do.inclusive-care'
import { Route as WhatWeDoHumanPotentialRouteImport } from './routes/what-we-do.human-potential'
import { Route as WhatWeDoPillarRouteImport } from './routes/what-we-do.$pillar'
import { Route as ProgramsWomensWellnessRouteImport } from './routes/programs.womens-wellness'
import { Route as ProgramsWomensHealthLifecycleRouteImport } from './routes/programs.womens-health-lifecycle'
import { Route as ProgramsTrainingCapacityBuildingRouteImport } from './routes/programs.training-capacity-building'
import { Route as ProgramsScholarshipsEducationRouteImport } from './routes/programs.scholarships-education'
import { Route as ProgramsResearchImpactAssessmentRouteImport } from './routes/programs.research-impact-assessment'
import { Route as ProgramsPreventiveHealthOutreachRouteImport } from './routes/programs.preventive-health-outreach'
import { Route as ProgramsDisabilityElderlyCareRouteImport } from './routes/programs.disability-elderly-care'
import { Route as ProgramsCommunityMentalHealthRouteImport } from './routes/programs.community-mental-health'
import { Route as ProgramsChwDevelopmentRouteImport } from './routes/programs.chw-development'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as PartnerCsrRouteImport } from './routes/partner.csr'
import { Route as ImpactStoriesRouteImport } from './routes/impact.stories'
import { Route as GetInvolvedVolunteerRouteImport } from './routes/get-involved.volunteer'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AboutVisionMissionRouteImport } from './routes/about.vision-mission'
import { Route as AboutValuesRouteImport } from './routes/about.values'
import { Route as AboutOurStoryRouteImport } from './routes/about.our-story'
import { Route as AboutOmniCareModelRouteImport } from './routes/about.omni-care-model'
import { Route as AboutLeadershipRouteImport } from './routes/about.leadership'
import { Route as AboutComplianceRouteImport } from './routes/about.compliance'
import { Route as AboutCareersRouteImport } from './routes/about.careers'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicFormsSubmitRouteImport } from './routes/api/public/forms/submit'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeguardingPolicyRoute = SafeguardingPolicyRouteImport.update({
  id: '/safeguarding-policy',
  path: '/safeguarding-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsroomRoute = NewsroomRouteImport.update({
  id: '/newsroom',
  path: '/newsroom',
  getParentRoute: () => rootRouteImport,
} as any)
const GetHelpRoute = GetHelpRouteImport.update({
  id: '/get-help',
  path: '/get-help',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationPolicyRoute = DonationPolicyRouteImport.update({
  id: '/donation-policy',
  path: '/donation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignUiInspoRoute = DesignUiInspoRouteImport.update({
  id: '/design-ui-inspo',
  path: '/design-ui-inspo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoIndexRoute = WhatWeDoIndexRouteImport.update({
  id: '/what-we-do/',
  path: '/what-we-do/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactIndexRoute = ImpactIndexRouteImport.update({
  id: '/impact/',
  path: '/impact/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedIndexRoute = GetInvolvedIndexRouteImport.update({
  id: '/get-involved/',
  path: '/get-involved/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoSocialGrowthRoute = WhatWeDoSocialGrowthRouteImport.update({
  id: '/what-we-do/social-growth',
  path: '/what-we-do/social-growth',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoMentalWellbeingRoute = WhatWeDoMentalWellbeingRouteImport.update({
  id: '/what-we-do/mental-wellbeing',
  path: '/what-we-do/mental-wellbeing',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoInclusiveCareRoute = WhatWeDoInclusiveCareRouteImport.update({
  id: '/what-we-do/inclusive-care',
  path: '/what-we-do/inclusive-care',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoHumanPotentialRoute = WhatWeDoHumanPotentialRouteImport.update({
  id: '/what-we-do/human-potential',
  path: '/what-we-do/human-potential',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoPillarRoute = WhatWeDoPillarRouteImport.update({
  id: '/what-we-do/$pillar',
  path: '/what-we-do/$pillar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsWomensWellnessRoute = ProgramsWomensWellnessRouteImport.update({
  id: '/programs/womens-wellness',
  path: '/programs/womens-wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsWomensHealthLifecycleRoute =
  ProgramsWomensHealthLifecycleRouteImport.update({
    id: '/programs/womens-health-lifecycle',
    path: '/programs/womens-health-lifecycle',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsTrainingCapacityBuildingRoute =
  ProgramsTrainingCapacityBuildingRouteImport.update({
    id: '/programs/training-capacity-building',
    path: '/programs/training-capacity-building',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsScholarshipsEducationRoute =
  ProgramsScholarshipsEducationRouteImport.update({
    id: '/programs/scholarships-education',
    path: '/programs/scholarships-education',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsResearchImpactAssessmentRoute =
  ProgramsResearchImpactAssessmentRouteImport.update({
    id: '/programs/research-impact-assessment',
    path: '/programs/research-impact-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsPreventiveHealthOutreachRoute =
  ProgramsPreventiveHealthOutreachRouteImport.update({
    id: '/programs/preventive-health-outreach',
    path: '/programs/preventive-health-outreach',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsDisabilityElderlyCareRoute =
  ProgramsDisabilityElderlyCareRouteImport.update({
    id: '/programs/disability-elderly-care',
    path: '/programs/disability-elderly-care',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsCommunityMentalHealthRoute =
  ProgramsCommunityMentalHealthRouteImport.update({
    id: '/programs/community-mental-health',
    path: '/programs/community-mental-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsChwDevelopmentRoute = ProgramsChwDevelopmentRouteImport.update({
  id: '/programs/chw-development',
  path: '/programs/chw-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerCsrRoute = PartnerCsrRouteImport.update({
  id: '/partner/csr',
  path: '/partner/csr',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactStoriesRoute = ImpactStoriesRouteImport.update({
  id: '/impact/stories',
  path: '/impact/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedVolunteerRoute = GetInvolvedVolunteerRouteImport.update({
  id: '/get-involved/volunteer',
  path: '/get-involved/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVisionMissionRoute = AboutVisionMissionRouteImport.update({
  id: '/about/vision-mission',
  path: '/about/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutValuesRoute = AboutValuesRouteImport.update({
  id: '/about/values',
  path: '/about/values',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOurStoryRoute = AboutOurStoryRouteImport.update({
  id: '/about/our-story',
  path: '/about/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOmniCareModelRoute = AboutOmniCareModelRouteImport.update({
  id: '/about/omni-care-model',
  path: '/about/omni-care-model',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutLeadershipRoute = AboutLeadershipRouteImport.update({
  id: '/about/leadership',
  path: '/about/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutComplianceRoute = AboutComplianceRouteImport.update({
  id: '/about/compliance',
  path: '/about/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCareersRoute = AboutCareersRouteImport.update({
  id: '/about/careers',
  path: '/about/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFormsSubmitRoute = ApiPublicFormsSubmitRouteImport.update({
  id: '/api/public/forms/submit',
  path: '/api/public/forms/submit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/design-ui-inspo': typeof DesignUiInspoRoute
  '/donate': typeof DonateRoute
  '/donation-policy': typeof DonationPolicyRoute
  '/get-help': typeof GetHelpRoute
  '/newsroom': typeof NewsroomRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/safeguarding-policy': typeof SafeguardingPolicyRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/about/careers': typeof AboutCareersRoute
  '/about/compliance': typeof AboutComplianceRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/omni-care-model': typeof AboutOmniCareModelRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/about/values': typeof AboutValuesRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/get-involved/volunteer': typeof GetInvolvedVolunteerRoute
  '/impact/stories': typeof ImpactStoriesRoute
  '/partner/csr': typeof PartnerCsrRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/chw-development': typeof ProgramsChwDevelopmentRoute
  '/programs/community-mental-health': typeof ProgramsCommunityMentalHealthRoute
  '/programs/disability-elderly-care': typeof ProgramsDisabilityElderlyCareRoute
  '/programs/preventive-health-outreach': typeof ProgramsPreventiveHealthOutreachRoute
  '/programs/research-impact-assessment': typeof ProgramsResearchImpactAssessmentRoute
  '/programs/scholarships-education': typeof ProgramsScholarshipsEducationRoute
  '/programs/training-capacity-building': typeof ProgramsTrainingCapacityBuildingRoute
  '/programs/womens-health-lifecycle': typeof ProgramsWomensHealthLifecycleRoute
  '/programs/womens-wellness': typeof ProgramsWomensWellnessRoute
  '/what-we-do/$pillar': typeof WhatWeDoPillarRoute
  '/what-we-do/human-potential': typeof WhatWeDoHumanPotentialRoute
  '/what-we-do/inclusive-care': typeof WhatWeDoInclusiveCareRoute
  '/what-we-do/mental-wellbeing': typeof WhatWeDoMentalWellbeingRoute
  '/what-we-do/social-growth': typeof WhatWeDoSocialGrowthRoute
  '/about/': typeof AboutIndexRoute
  '/get-involved/': typeof GetInvolvedIndexRoute
  '/impact/': typeof ImpactIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/what-we-do/': typeof WhatWeDoIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/forms/submit': typeof ApiPublicFormsSubmitRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/design-ui-inspo': typeof DesignUiInspoRoute
  '/donate': typeof DonateRoute
  '/donation-policy': typeof DonationPolicyRoute
  '/get-help': typeof GetHelpRoute
  '/newsroom': typeof NewsroomRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/safeguarding-policy': typeof SafeguardingPolicyRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/about/careers': typeof AboutCareersRoute
  '/about/compliance': typeof AboutComplianceRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/omni-care-model': typeof AboutOmniCareModelRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/about/values': typeof AboutValuesRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/get-involved/volunteer': typeof GetInvolvedVolunteerRoute
  '/impact/stories': typeof ImpactStoriesRoute
  '/partner/csr': typeof PartnerCsrRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/chw-development': typeof ProgramsChwDevelopmentRoute
  '/programs/community-mental-health': typeof ProgramsCommunityMentalHealthRoute
  '/programs/disability-elderly-care': typeof ProgramsDisabilityElderlyCareRoute
  '/programs/preventive-health-outreach': typeof ProgramsPreventiveHealthOutreachRoute
  '/programs/research-impact-assessment': typeof ProgramsResearchImpactAssessmentRoute
  '/programs/scholarships-education': typeof ProgramsScholarshipsEducationRoute
  '/programs/training-capacity-building': typeof ProgramsTrainingCapacityBuildingRoute
  '/programs/womens-health-lifecycle': typeof ProgramsWomensHealthLifecycleRoute
  '/programs/womens-wellness': typeof ProgramsWomensWellnessRoute
  '/what-we-do/$pillar': typeof WhatWeDoPillarRoute
  '/what-we-do/human-potential': typeof WhatWeDoHumanPotentialRoute
  '/what-we-do/inclusive-care': typeof WhatWeDoInclusiveCareRoute
  '/what-we-do/mental-wellbeing': typeof WhatWeDoMentalWellbeingRoute
  '/what-we-do/social-growth': typeof WhatWeDoSocialGrowthRoute
  '/about': typeof AboutIndexRoute
  '/get-involved': typeof GetInvolvedIndexRoute
  '/impact': typeof ImpactIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/what-we-do': typeof WhatWeDoIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/forms/submit': typeof ApiPublicFormsSubmitRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/design-ui-inspo': typeof DesignUiInspoRoute
  '/donate': typeof DonateRoute
  '/donation-policy': typeof DonationPolicyRoute
  '/get-help': typeof GetHelpRoute
  '/newsroom': typeof NewsroomRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/safeguarding-policy': typeof SafeguardingPolicyRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/about/careers': typeof AboutCareersRoute
  '/about/compliance': typeof AboutComplianceRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/omni-care-model': typeof AboutOmniCareModelRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/about/values': typeof AboutValuesRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/get-involved/volunteer': typeof GetInvolvedVolunteerRoute
  '/impact/stories': typeof ImpactStoriesRoute
  '/partner/csr': typeof PartnerCsrRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/chw-development': typeof ProgramsChwDevelopmentRoute
  '/programs/community-mental-health': typeof ProgramsCommunityMentalHealthRoute
  '/programs/disability-elderly-care': typeof ProgramsDisabilityElderlyCareRoute
  '/programs/preventive-health-outreach': typeof ProgramsPreventiveHealthOutreachRoute
  '/programs/research-impact-assessment': typeof ProgramsResearchImpactAssessmentRoute
  '/programs/scholarships-education': typeof ProgramsScholarshipsEducationRoute
  '/programs/training-capacity-building': typeof ProgramsTrainingCapacityBuildingRoute
  '/programs/womens-health-lifecycle': typeof ProgramsWomensHealthLifecycleRoute
  '/programs/womens-wellness': typeof ProgramsWomensWellnessRoute
  '/what-we-do/$pillar': typeof WhatWeDoPillarRoute
  '/what-we-do/human-potential': typeof WhatWeDoHumanPotentialRoute
  '/what-we-do/inclusive-care': typeof WhatWeDoInclusiveCareRoute
  '/what-we-do/mental-wellbeing': typeof WhatWeDoMentalWellbeingRoute
  '/what-we-do/social-growth': typeof WhatWeDoSocialGrowthRoute
  '/about/': typeof AboutIndexRoute
  '/get-involved/': typeof GetInvolvedIndexRoute
  '/impact/': typeof ImpactIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/what-we-do/': typeof WhatWeDoIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/forms/submit': typeof ApiPublicFormsSubmitRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/contact'
    | '/design-ui-inspo'
    | '/donate'
    | '/donation-policy'
    | '/get-help'
    | '/newsroom'
    | '/privacy-policy'
    | '/safeguarding-policy'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/about/careers'
    | '/about/compliance'
    | '/about/leadership'
    | '/about/omni-care-model'
    | '/about/our-story'
    | '/about/values'
    | '/about/vision-mission'
    | '/email/unsubscribe'
    | '/get-involved/volunteer'
    | '/impact/stories'
    | '/partner/csr'
    | '/programs/$slug'
    | '/programs/chw-development'
    | '/programs/community-mental-health'
    | '/programs/disability-elderly-care'
    | '/programs/preventive-health-outreach'
    | '/programs/research-impact-assessment'
    | '/programs/scholarships-education'
    | '/programs/training-capacity-building'
    | '/programs/womens-health-lifecycle'
    | '/programs/womens-wellness'
    | '/what-we-do/$pillar'
    | '/what-we-do/human-potential'
    | '/what-we-do/inclusive-care'
    | '/what-we-do/mental-wellbeing'
    | '/what-we-do/social-growth'
    | '/about/'
    | '/get-involved/'
    | '/impact/'
    | '/programs/'
    | '/what-we-do/'
    | '/lovable/email/suppression'
    | '/api/public/forms/submit'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/contact'
    | '/design-ui-inspo'
    | '/donate'
    | '/donation-policy'
    | '/get-help'
    | '/newsroom'
    | '/privacy-policy'
    | '/safeguarding-policy'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/about/careers'
    | '/about/compliance'
    | '/about/leadership'
    | '/about/omni-care-model'
    | '/about/our-story'
    | '/about/values'
    | '/about/vision-mission'
    | '/email/unsubscribe'
    | '/get-involved/volunteer'
    | '/impact/stories'
    | '/partner/csr'
    | '/programs/$slug'
    | '/programs/chw-development'
    | '/programs/community-mental-health'
    | '/programs/disability-elderly-care'
    | '/programs/preventive-health-outreach'
    | '/programs/research-impact-assessment'
    | '/programs/scholarships-education'
    | '/programs/training-capacity-building'
    | '/programs/womens-health-lifecycle'
    | '/programs/womens-wellness'
    | '/what-we-do/$pillar'
    | '/what-we-do/human-potential'
    | '/what-we-do/inclusive-care'
    | '/what-we-do/mental-wellbeing'
    | '/what-we-do/social-growth'
    | '/about'
    | '/get-involved'
    | '/impact'
    | '/programs'
    | '/what-we-do'
    | '/lovable/email/suppression'
    | '/api/public/forms/submit'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/contact'
    | '/design-ui-inspo'
    | '/donate'
    | '/donation-policy'
    | '/get-help'
    | '/newsroom'
    | '/privacy-policy'
    | '/safeguarding-policy'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/about/careers'
    | '/about/compliance'
    | '/about/leadership'
    | '/about/omni-care-model'
    | '/about/our-story'
    | '/about/values'
    | '/about/vision-mission'
    | '/email/unsubscribe'
    | '/get-involved/volunteer'
    | '/impact/stories'
    | '/partner/csr'
    | '/programs/$slug'
    | '/programs/chw-development'
    | '/programs/community-mental-health'
    | '/programs/disability-elderly-care'
    | '/programs/preventive-health-outreach'
    | '/programs/research-impact-assessment'
    | '/programs/scholarships-education'
    | '/programs/training-capacity-building'
    | '/programs/womens-health-lifecycle'
    | '/programs/womens-wellness'
    | '/what-we-do/$pillar'
    | '/what-we-do/human-potential'
    | '/what-we-do/inclusive-care'
    | '/what-we-do/mental-wellbeing'
    | '/what-we-do/social-growth'
    | '/about/'
    | '/get-involved/'
    | '/impact/'
    | '/programs/'
    | '/what-we-do/'
    | '/lovable/email/suppression'
    | '/api/public/forms/submit'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ContactRoute: typeof ContactRoute
  DesignUiInspoRoute: typeof DesignUiInspoRoute
  DonateRoute: typeof DonateRoute
  DonationPolicyRoute: typeof DonationPolicyRoute
  GetHelpRoute: typeof GetHelpRoute
  NewsroomRoute: typeof NewsroomRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SafeguardingPolicyRoute: typeof SafeguardingPolicyRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AboutCareersRoute: typeof AboutCareersRoute
  AboutComplianceRoute: typeof AboutComplianceRoute
  AboutLeadershipRoute: typeof AboutLeadershipRoute
  AboutOmniCareModelRoute: typeof AboutOmniCareModelRoute
  AboutOurStoryRoute: typeof AboutOurStoryRoute
  AboutValuesRoute: typeof AboutValuesRoute
  AboutVisionMissionRoute: typeof AboutVisionMissionRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GetInvolvedVolunteerRoute: typeof GetInvolvedVolunteerRoute
  ImpactStoriesRoute: typeof ImpactStoriesRoute
  PartnerCsrRoute: typeof PartnerCsrRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProgramsChwDevelopmentRoute: typeof ProgramsChwDevelopmentRoute
  ProgramsCommunityMentalHealthRoute: typeof ProgramsCommunityMentalHealthRoute
  ProgramsDisabilityElderlyCareRoute: typeof ProgramsDisabilityElderlyCareRoute
  ProgramsPreventiveHealthOutreachRoute: typeof ProgramsPreventiveHealthOutreachRoute
  ProgramsResearchImpactAssessmentRoute: typeof ProgramsResearchImpactAssessmentRoute
  ProgramsScholarshipsEducationRoute: typeof ProgramsScholarshipsEducationRoute
  ProgramsTrainingCapacityBuildingRoute: typeof ProgramsTrainingCapacityBuildingRoute
  ProgramsWomensHealthLifecycleRoute: typeof ProgramsWomensHealthLifecycleRoute
  ProgramsWomensWellnessRoute: typeof ProgramsWomensWellnessRoute
  WhatWeDoPillarRoute: typeof WhatWeDoPillarRoute
  WhatWeDoHumanPotentialRoute: typeof WhatWeDoHumanPotentialRoute
  WhatWeDoInclusiveCareRoute: typeof WhatWeDoInclusiveCareRoute
  WhatWeDoMentalWellbeingRoute: typeof WhatWeDoMentalWellbeingRoute
  WhatWeDoSocialGrowthRoute: typeof WhatWeDoSocialGrowthRoute
  AboutIndexRoute: typeof AboutIndexRoute
  GetInvolvedIndexRoute: typeof GetInvolvedIndexRoute
  ImpactIndexRoute: typeof ImpactIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  WhatWeDoIndexRoute: typeof WhatWeDoIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicFormsSubmitRoute: typeof ApiPublicFormsSubmitRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safeguarding-policy': {
      id: '/safeguarding-policy'
      path: '/safeguarding-policy'
      fullPath: '/safeguarding-policy'
      preLoaderRoute: typeof SafeguardingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom': {
      id: '/newsroom'
      path: '/newsroom'
      fullPath: '/newsroom'
      preLoaderRoute: typeof NewsroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-help': {
      id: '/get-help'
      path: '/get-help'
      fullPath: '/get-help'
      preLoaderRoute: typeof GetHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donation-policy': {
      id: '/donation-policy'
      path: '/donation-policy'
      fullPath: '/donation-policy'
      preLoaderRoute: typeof DonationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-ui-inspo': {
      id: '/design-ui-inspo'
      path: '/design-ui-inspo'
      fullPath: '/design-ui-inspo'
      preLoaderRoute: typeof DesignUiInspoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/': {
      id: '/what-we-do/'
      path: '/what-we-do'
      fullPath: '/what-we-do/'
      preLoaderRoute: typeof WhatWeDoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact/': {
      id: '/impact/'
      path: '/impact'
      fullPath: '/impact/'
      preLoaderRoute: typeof ImpactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/': {
      id: '/get-involved/'
      path: '/get-involved'
      fullPath: '/get-involved/'
      preLoaderRoute: typeof GetInvolvedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/social-growth': {
      id: '/what-we-do/social-growth'
      path: '/what-we-do/social-growth'
      fullPath: '/what-we-do/social-growth'
      preLoaderRoute: typeof WhatWeDoSocialGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/mental-wellbeing': {
      id: '/what-we-do/mental-wellbeing'
      path: '/what-we-do/mental-wellbeing'
      fullPath: '/what-we-do/mental-wellbeing'
      preLoaderRoute: typeof WhatWeDoMentalWellbeingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/inclusive-care': {
      id: '/what-we-do/inclusive-care'
      path: '/what-we-do/inclusive-care'
      fullPath: '/what-we-do/inclusive-care'
      preLoaderRoute: typeof WhatWeDoInclusiveCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/human-potential': {
      id: '/what-we-do/human-potential'
      path: '/what-we-do/human-potential'
      fullPath: '/what-we-do/human-potential'
      preLoaderRoute: typeof WhatWeDoHumanPotentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/$pillar': {
      id: '/what-we-do/$pillar'
      path: '/what-we-do/$pillar'
      fullPath: '/what-we-do/$pillar'
      preLoaderRoute: typeof WhatWeDoPillarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/womens-wellness': {
      id: '/programs/womens-wellness'
      path: '/programs/womens-wellness'
      fullPath: '/programs/womens-wellness'
      preLoaderRoute: typeof ProgramsWomensWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/womens-health-lifecycle': {
      id: '/programs/womens-health-lifecycle'
      path: '/programs/womens-health-lifecycle'
      fullPath: '/programs/womens-health-lifecycle'
      preLoaderRoute: typeof ProgramsWomensHealthLifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/training-capacity-building': {
      id: '/programs/training-capacity-building'
      path: '/programs/training-capacity-building'
      fullPath: '/programs/training-capacity-building'
      preLoaderRoute: typeof ProgramsTrainingCapacityBuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/scholarships-education': {
      id: '/programs/scholarships-education'
      path: '/programs/scholarships-education'
      fullPath: '/programs/scholarships-education'
      preLoaderRoute: typeof ProgramsScholarshipsEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/research-impact-assessment': {
      id: '/programs/research-impact-assessment'
      path: '/programs/research-impact-assessment'
      fullPath: '/programs/research-impact-assessment'
      preLoaderRoute: typeof ProgramsResearchImpactAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/preventive-health-outreach': {
      id: '/programs/preventive-health-outreach'
      path: '/programs/preventive-health-outreach'
      fullPath: '/programs/preventive-health-outreach'
      preLoaderRoute: typeof ProgramsPreventiveHealthOutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/disability-elderly-care': {
      id: '/programs/disability-elderly-care'
      path: '/programs/disability-elderly-care'
      fullPath: '/programs/disability-elderly-care'
      preLoaderRoute: typeof ProgramsDisabilityElderlyCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/community-mental-health': {
      id: '/programs/community-mental-health'
      path: '/programs/community-mental-health'
      fullPath: '/programs/community-mental-health'
      preLoaderRoute: typeof ProgramsCommunityMentalHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/chw-development': {
      id: '/programs/chw-development'
      path: '/programs/chw-development'
      fullPath: '/programs/chw-development'
      preLoaderRoute: typeof ProgramsChwDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/csr': {
      id: '/partner/csr'
      path: '/partner/csr'
      fullPath: '/partner/csr'
      preLoaderRoute: typeof PartnerCsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact/stories': {
      id: '/impact/stories'
      path: '/impact/stories'
      fullPath: '/impact/stories'
      preLoaderRoute: typeof ImpactStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/volunteer': {
      id: '/get-involved/volunteer'
      path: '/get-involved/volunteer'
      fullPath: '/get-involved/volunteer'
      preLoaderRoute: typeof GetInvolvedVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/vision-mission': {
      id: '/about/vision-mission'
      path: '/about/vision-mission'
      fullPath: '/about/vision-mission'
      preLoaderRoute: typeof AboutVisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/values': {
      id: '/about/values'
      path: '/about/values'
      fullPath: '/about/values'
      preLoaderRoute: typeof AboutValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/our-story': {
      id: '/about/our-story'
      path: '/about/our-story'
      fullPath: '/about/our-story'
      preLoaderRoute: typeof AboutOurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/omni-care-model': {
      id: '/about/omni-care-model'
      path: '/about/omni-care-model'
      fullPath: '/about/omni-care-model'
      preLoaderRoute: typeof AboutOmniCareModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/leadership': {
      id: '/about/leadership'
      path: '/about/leadership'
      fullPath: '/about/leadership'
      preLoaderRoute: typeof AboutLeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/compliance': {
      id: '/about/compliance'
      path: '/about/compliance'
      fullPath: '/about/compliance'
      preLoaderRoute: typeof AboutComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/careers': {
      id: '/about/careers'
      path: '/about/careers'
      fullPath: '/about/careers'
      preLoaderRoute: typeof AboutCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/submit': {
      id: '/api/public/forms/submit'
      path: '/api/public/forms/submit'
      fullPath: '/api/public/forms/submit'
      preLoaderRoute: typeof ApiPublicFormsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  ContactRoute: ContactRoute,
  DesignUiInspoRoute: DesignUiInspoRoute,
  DonateRoute: DonateRoute,
  DonationPolicyRoute: DonationPolicyRoute,
  GetHelpRoute: GetHelpRoute,
  NewsroomRoute: NewsroomRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SafeguardingPolicyRoute: SafeguardingPolicyRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AboutCareersRoute: AboutCareersRoute,
  AboutComplianceRoute: AboutComplianceRoute,
  AboutLeadershipRoute: AboutLeadershipRoute,
  AboutOmniCareModelRoute: AboutOmniCareModelRoute,
  AboutOurStoryRoute: AboutOurStoryRoute,
  AboutValuesRoute: AboutValuesRoute,
  AboutVisionMissionRoute: AboutVisionMissionRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GetInvolvedVolunteerRoute: GetInvolvedVolunteerRoute,
  ImpactStoriesRoute: ImpactStoriesRoute,
  PartnerCsrRoute: PartnerCsrRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProgramsChwDevelopmentRoute: ProgramsChwDevelopmentRoute,
  ProgramsCommunityMentalHealthRoute: ProgramsCommunityMentalHealthRoute,
  ProgramsDisabilityElderlyCareRoute: ProgramsDisabilityElderlyCareRoute,
  ProgramsPreventiveHealthOutreachRoute: ProgramsPreventiveHealthOutreachRoute,
  ProgramsResearchImpactAssessmentRoute: ProgramsResearchImpactAssessmentRoute,
  ProgramsScholarshipsEducationRoute: ProgramsScholarshipsEducationRoute,
  ProgramsTrainingCapacityBuildingRoute: ProgramsTrainingCapacityBuildingRoute,
  ProgramsWomensHealthLifecycleRoute: ProgramsWomensHealthLifecycleRoute,
  ProgramsWomensWellnessRoute: ProgramsWomensWellnessRoute,
  WhatWeDoPillarRoute: WhatWeDoPillarRoute,
  WhatWeDoHumanPotentialRoute: WhatWeDoHumanPotentialRoute,
  WhatWeDoInclusiveCareRoute: WhatWeDoInclusiveCareRoute,
  WhatWeDoMentalWellbeingRoute: WhatWeDoMentalWellbeingRoute,
  WhatWeDoSocialGrowthRoute: WhatWeDoSocialGrowthRoute,
  AboutIndexRoute: AboutIndexRoute,
  GetInvolvedIndexRoute: GetInvolvedIndexRoute,
  ImpactIndexRoute: ImpactIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  WhatWeDoIndexRoute: WhatWeDoIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicFormsSubmitRoute: ApiPublicFormsSubmitRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
